### ISSUE TITLE
PAUSE button doesn't show feedback

### ISSUE THREAD

**Issue by ShawnDriscoll** [MariyaSha/PythonMusicPlayer#1]
Hate to bug you on this. But the PAUSE button doesn't switch to PAUSED like it does in the non-dearpygui version. If you press PAUSE before playing anything, the app seems to freeze/lockup until you press the STOP button. Then you can press PLAY to play.

**Comment by ShawnDriscoll** [comment]
closing

**Comment by MariyaSha** [comment]
aha! thanks for letting me know, I'll be sure to fix it before I film a tutorial on it (would take me some time though... I haven't revisited this app in a while unfortunately)
